### ISSUE TITLE
Compile script for Windows/mac

### ISSUE THREAD

**Issue by jeremymeyers** [actionless/firefox_search_jackett#1]
is there a way to do this?

**Comment by actionless** [comment]
`brew search 7z`

**Comment by jeremymeyers** [comment]
(brew is for mac, not PC). maybe you mean chocolatey?

**Comment by actionless** [comment]
you asked about windows or mac, and i have only mac and linux in my possession

for windows idk

**Comment by actionless** [comment]
if you'll come up with a cmd or powershell build script for windows, feel free to make a PR here -- mb other people will also find it useful later
